sudo: required
dist: trusty
language: node_js
node_js:
  - "9"
env:
  global:
    - NODE_ENV=development
    before_install:
- npm install n
- sudo ./node_modules/.bin/n stable
- rm -rf ~/.nvm
- cd backend
script:
  - npm install
  - "sudo $(which npm) test"
